#!/bin/bash

### BEGIN INIT INFO
# Provides:        if-snmp-agent
# Required-Start:  $network $syslog snmpd
# Required-Stop:
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: SNMP agent for packet broker MIBs
### END INIT INFO

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
LOG=/var/log/if-snmp-agent

. /lib/lsb/init-functions

test -f /etc/default/packet-broker
source /etc/default/packet-broker

SUBAGENT=${BASE}/snabb-snmp-subagent/subagent
DAEMON="/usr/bin/perl ${SUBAGENT}/bin/interface"
IFINDEX=${BASE}/packet-broker/ifindex/Wedge-100bf-32X

PIDFILE=/var/run/if_snmp_agent.pid

case $1 in
    start)
        mkdir -p $IFMIBS_DIR
        log_daemon_msg "Starting interface SNMP subagent" "if-snmp-agent"
        export PERLLIB=${SUBAGENT}/lib
        set +e
        start-stop-daemon --start --make-pidfile --pidfile $PIDFILE \
                          --startas $DAEMON --background --no-close \
                          -- --ifindex=$IFINDEX --shmem-dir=$IFMIBS_DIR >>$LOG 2>&1
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping interface SNMP subagent" "if-snmp-agent"
        start-stop-daemon --remove-pidfile --pidfile $PIDFILE --stop --startas $DAEMON --retry=INT/30/KILL/5
        log_end_msg $?
        ;;
    restart|force-reload)
        $0 stop && sleep 2 && $0 start
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON "Interface SNMP subagent"
        ;;
    *)
	echo "Usage: $0 {start|stop|restart|force-reload|status}"
	exit 2
	;;
esac
