---
- hosts: wedges
  remote_user: ansible
  become: yes
  tasks:
    - name: Set DHCP
      become: yes
      blockinfile:
        dest: /etc/network/interfaces
        block: |
          auto ma1
          iface ma1 inet dhcp

    ## Right after the ONL installer has run, the interface is
    ## configured by DHCP but not controlled by
    ## /etc/network/interfaces. This task should be a no-op
    ## after the playbook has run for the first time.
    - name: Activate DHCP
      shell: ifquery ma1 || ifconfig ma1 down && ifup ma1
      
    - name: Remove NTP pool servers
      lineinfile:
        dest: /etc/ntp.conf
        state: absent
        regexp: ^pool
        
    - name: Add NTP server
      blockinfile:
        dest: /etc/ntp.conf
        block: |
          server ntp.net.switch.ch iburst
          
    - name: Set localtime
      copy:
        remote_src: yes
        src: /usr/share/zoneinfo/Europe/Zurich
        dest: /etc/localtime
        
    - name: Set timezone
      shell: echo Europe/Zurich >/etc/timezone
      
    - name: Create group for Barefoot SDE
      group:
        name: bfsde
        
    - name: Create user for Barefoot SDE
      user:
        name: bfsde
        group: bfsde
        shell: /usr/bin/false
        password: '!'
        
    - name: Install the Barefoot SDE
      unarchive:
        src: "{{ bf_sde_src_path }}/bf-sde/bf-sde-{{ bf_sde_version }}.tar"
        dest: "{{ bf_sde_dst_path }}"
        owner: bfsde
        group: bfsde
        mode: '0775'
        creates: "{{ bf_sde_dst_path }}/bf-sde-{{ bf_sde_version }}"
    
    - name: Install the pre-built Barefoot SDE artefacts
      unarchive:
        src: "{{ bf_sde_src_path }}/bf-sde/bf-sde-{{ bf_sde_version }}-install.tar"
        dest: "{{ bf_sde_dst_path }}/bf-sde-{{ bf_sde_version }}"
        owner: bfsde
        group: bfsde
        mode: '0775'
        creates: "{{ bf_sde_dst_path }}/bf-sde-{{ bf_sde_version }}/install"
    
    - name: Install the Barefoot SDE tools
      unarchive:
        src: "{{ bf_sde_src_path }}/bf-sde/ba-102-tools-2019-09-09.tar"
        dest: "{{ bf_sde_dst_path }}"
        owner: bfsde
        group: bfsde
        mode: '0775'
        creates: "{{ bf_sde_dst_path }}/tools"
    
    - name: Copy Barefoot SDE dependencies
      become: no
      unarchive:
        src: "{{ wedge_dependencies_path }}"
        dest: /tmp/
        creates: /tmp/dependencies

    - name: Patch dependencies install script
      become: no
      replace:
        dest: /tmp/dependencies/install.sh
        regexp: '^make'
        replace: make -j8
        
    - name: Install Barefoot SDE dependencies (grab a coffe, this takes about 30 minutes)
      shell:
        cmd: ./install.sh && touch {{ bf_sde_dst_path }}/.dependencies_installed
        creates: "{{ bf_sde_dst_path }}/.dependencies_installed"
        chdir: /tmp/dependencies
    
    - name: Create /data
      file:
        path: /data
        state: directory
        mode: '0777'
        
    - name: Install packet-broker software
      become: no
      git:
        repo: https://gitlab+deploy-token-65:vQFnqMMrUy6K8Cwv4Hxq@gitlab-int.switch.ch/network/packet-broker.git
        version: dfeff7bf1c
        accept_hostkey: yes
        dest: /data/packet-broker

    ## This should be done automatically by the next copy
    ## operation (trailing slash on /etc/packet-broker/),
    ## but this doesn't seem to happen for remote_src
    - name: Create packet broker config directory
      file:
        path: /etc/packet-broker
        state: directory
        
    - name: Install packet broker JSON schema and initial config
      with_items: [ schema.json, config.json ]
      copy:
        remote_src: yes
        src: /data/packet-broker/{{ item }}
        dest: /etc/packet-broker/

    - name: Create packet broker service defaults
      blockinfile:
        dest: /etc/default/packet-broker
        create: yes
        block: |
          BASE=/data/packet-broker
          CONFIG_DIR=/etc/packet-broker
          IFMIBS_DIR=/var/run/packet-broker
          SDE_VERSION={{ bf_sde_version }}
          export SDE={{ bf_sde_dst_path }}/bf-sde-${SDE_VERSION}
          export SDE_INSTALL=${SDE}/install
          CONNECT_RETRIES=30

    - name: Create packet broker service
      copy:
        src: services/packet-broker
        dest: /etc/init.d/
        mode: '0755'

    - name: Create packet broker configure service
      copy:
        src: services/packet-broker-configd
        dest: /etc/init.d/
        mode: '0755'

    - name: Configure snmpd service
      copy:
        src: services/snmpd.conf
        dest: /etc/snmp/

    - name: Set snmpd options
      blockinfile:
        dest: /etc/default/snmpd
        block:
          SNMPDOPTS="${SNMPDOPTS} -I -ifTable"
          
    - name: Install SNMP agent
      become: no
      git:
        repo: https://github.com/alexandergall/snabb-snmp-subagent.git
        version: v4
        dest: /data/snabb-snmp-subagent

    - name: apt-get update
      command: apt-get update
      
    - name: Install snmp subagent dependencies
      with_items: [ libsnmp-perl, libnet-snmp-perl, libsys-mmap-perl ]
      apt:
        name: "{{ item }}"
        state: present

    - name: Add snmp subagent interface.conf
      copy:
        src: services/interface.conf
        dest: /etc/snmp/
        
    - name: Create snmp subagent service
      copy:
        src: services/if-snmp-agent
        dest: /etc/init.d/
        mode: '0755'

    - name: (Re)start services
      with_items:
        - { name: ntp, state: started }
        - { name: packet-broker, state: started }
        - { name: packet-broker-configd, state: started }
        - { name: snmpd, state: restarted }
        - { name: if-snmp-agent, state: started }
      service:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      
    - name: Set Barefoot SDE environment in /etc/profile
      blockinfile:
        dest: /etc/profile
        block: |
          export SDE={{ bf_sde_dst_path }}/bf-sde-{{ bf_sde_version }}
          export SDE_INSTALL=${SDE}/install
          PATH=${SDE_INSTALL}/bin:${PATH}

    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
                          
    - name: Create users
      with_items:
        - { name: gall, comment: "Alexander Gall" }
        - { name: leinen, comment: "Simon Leinen" }
        - { name: welti, comment: "Chris Welti" }
        - { name: schmid, comment: "Ulrich Schmid" }
        - { name: mauchle, comment: "Fabian Mauchle" }

      user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        groups: sudo
        shell: /bin/bash

    - name: Add ssh keys
      with_items:
        - { user: gall,
        key:
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCravbHR+YSsvUcmiTBCm+1KbCcHOTALfAZElm/XRpgda5j3aZJLELUgwtzdz67LCjGfjqzNlw8amUfnYyhtO2AWdwGWrusH2vaG3Uh+5aemI3KLRWubmiOQra3U51/9uMjYaAgKSA5tBJpim1NWFqpGLsEVtELPfnS6BahAms21ncipW9ZNyU2n1+9Hj9F+PquivYFncgfmdWnyuKCA/j/LymDrUrAhIBq1JmqH4xXwnBC88+2jN9l11x1eJ6sapJxKkTbE6Yd4XCJ7V2FkFjsGLx+zx+8somXWKOnZZ3tqTZlDNbRpsoy7nAbh1W/b35KfMOSuNmhfg3bfPBT+65f17UIL2Ys5SfkinLAFIEn/mN5HRKAaiRBnzpSuvlJpBspIaebo8U5UF5ftW+0WgM9PxRvPcRFaEcGIJsFs892078JI/RNOzTNc/Jso4Md5GwbaIMNh9oI0Iq27tvOfY1oaMeiFPHoBcEJHH37NZbl4QgFaO9ORC1AMClBYaAfmhmXYyFOrFw1DvHvKTWUg9RCGBbTO5gKspr7IMPTYL3DC/pNODM3O5efn4Yvolw7iiS+7s9O9ObvVLzMSJggFcFSWGGVrXl4qwY/wFzshATFKaRdkMiB5pW6QO5H0sjtY68fZYAeFUG6caMF6nVIiw4DWe+yJSNNtE/LV87VG9nIMw== gall@switch.ch }
        - { user: leinen,
        key:
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKYviHb6GPnzfpS/rRBkv4oUVCFbqil29XRPLbxkYf4nO3O37TUp7WGrsCeB8cf8IUEEYry8Cx2rAzYRRHNTQ0yzluD69D+5O+7b0MCf0gmma9eygXD/W7r69Zt1GmHVzPLd4YLoPQ3Hn6HxVPZcxXh7eTq1ItQuBAbUaKUlpMWFRT9U/DVBBCaQjKf0SH9Ev9jGJA60cvgY497vlj86F5Y+npD7hhCJJaUdce+LI8FVYGwFX7jC/9A+hvEQYpcSjjg9ChGTC0Mgk/O6Rl14vsbkBdI6HERvlolvZ2/Qw8i6lnXHqM7d5KkGXnTVI5hjwZDl4cg5N+UXMPa39jKnT5 leinen@macsl-10966.local }
        - { user: welti,
        key:
          ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEA4ZBNhxuJ9mhP6fho+CkzzxQTnvzrsyCl2uk/SgW1uaMPhwZ0Nr2ImxukAVM4z5VaZdNkPceK1K6MnE9RBlrsF9STkuoesp/alCUB2vFya0mXGRhhXESQ5wqgsqpK1sEHFBliGY84xUlH92b1+TuD5gmgoqNz5e7EeisXoVCGG1E= welti@sleipnir }
        - { user: schmid,
        key:
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtfDCElyUpt/08ZjM6uq4OC4Gwvd5Q8+O3aCqtnJFHzJxGL8fo0Kpvx1+7iM6cQBSPnMpS++JRQqkGFCZO7QNV4pCndMEziOSxS0ouk4pAzHk5IDTi0tliNijpPmq7ifxE9RZS4y7ce7r7HIwfN/PJH2XMqVUbGPZ1iK9kVVR9rfI4ybFvidmYOwrbxAhsH6McDFqSqL5oGcvjw5vU7CJVAKksrzsaao/IScXK12ZHoKw3mdP/Hu/DyaG9E0ckTaXG9Zs6bdNKTfHduHFwHed24L5N/MVhRZ25Rezmj2A6A4q4Cv+sAPzScKWA3mIoeH81tPlHDZ0hFaPfo0zd/GPB schmid@xobeee }
        - { user: mauchle,
        key:
          ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAp8b3fRzfiWAH6T0R22XUmu62JYkJHLIqvWPjT9CxPBpKiF76ElZZjL4ZCoLGAUtk3+DUadwsYZh8Qz9uhWp3FFYKbDQk9MM3Sca6PocwH8L2YGOO3S0EVbkDZf3GoFgf8E3qvHW3A8CdzK/0/A6UNO7ASfM+AGRjW/3+6iklPGbCSpGYdqePtfNHGVp0hruDVHBPMcOvH6MuOO8Vto9S58Z9FjG5ini2OYNOgxg8Bymg55RS9PVHsucp6dCS/tfRf5x52LVkfOH2UutwFD/AhWV+I481e4kCnuzzcqlPBuLb3tcptoRzWfcv5IHs9IgrZ8RSvdW8cbAPrS6yNAwcKw== mauchle@macfma.switch.ch }
      authorized_key:
        user: "{{ item.user }}"
        key: "{{ item.key }}"
        state: present
          
