#!/bin/bash

### BEGIN INIT INFO
# Provides:        packet-broker-configure
# Required-Start:  $network $syslog packet-broker
# Required-Stop:   
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: packet-broker P4 configuration daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
LOG=/var/log/packet-broker-configure

. /lib/lsb/init-functions

BASE=/home/gall
SDE=${BASE}/bf-sde-9.1.0
TOOLS=${BASE}/tools
CONFIGURE=${BASE}/packet-broker/configure.py

cd $SDE
source $TOOLS/set_sde.bash

test -x $RUN_SWITCHD || exit 5

PIDFILE=/var/run/pb-configure.pid

case $1 in
    start)
        log_daemon_msg "Starting packet-broker configuration daemon" "pb-configure"
        start-stop-daemon --start --make-pidfile --pidfile $PIDFILE \
                          --startas $CONFIGURE --background --no-close >>$LOG 2>&1
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping packet-broker configuration daemon" "pb-configure"
        start-stop-daemon --remove-pidfile --pidfile $PIDFILE --stop --startas $CONFIGURE --retry=INT/30/KILL/5
        log_end_msg $?
        ;;
    restart|force-reload)
        $0 stop && sleep 2 && $0 start
        ;;
    reload)
        kill -HUP $(cat $PIDFILE)
        ;;
    status)
        status_of_proc -p $PIDFILE $CONFIGURE "Packet-broker configuration daemon"
        ;;
    *)
	echo "Usage: $0 {start|stop|restart|force-reload|status}"
	exit 2
	;;
esac
