#!/bin/bash

### BEGIN INIT INFO
# Provides:        packet-broker
# Required-Start:  $network $syslog
# Required-Stop:   $network $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start bf_switchd with packet-broker P4 program
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
LOG=/var/log/bf_switchd

. /lib/lsb/init-functions

BASE=/home/gall
SDE=${BASE}/bf-sde-9.1.0
TOOLS=${BASE}/tools

cd $SDE
source $TOOLS/set_sde.bash

RUN_SWITCHD=${SDE}/run_switchd.sh

test -x $RUN_SWITCHD || exit 5

if ! lsmod | grep bf_kdrv >/dev/null; then
    $SDE_INSTALL/bin/bf_kdrv_mod_load $SDE_INSTALL
fi

case $1 in
	start)
		log_daemon_msg "Starting packet-broker server" "bf_switchd"
		start-stop-daemon --start --name bf_switchd \
                                  --startas $RUN_SWITCHD --background --no-close \
                                  -- -p packet_broker -- --background >>$LOG 2>&1
		log_end_msg $?
  		;;
	stop)
		log_daemon_msg "Stopping packet-broker server" "bf_switchd"
		start-stop-daemon --stop --name bf_switchd --retry=INT/30/KILL/5
		log_end_msg $?
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc bf_switchd "Packet-broker server"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|force-reload|status}"
		exit 2
		;;
esac
