#!/bin/bash

### BEGIN INIT INFO
# Provides:        packet-broker-configd
# Required-Start:  $network $syslog packet-broker
# Required-Stop:   
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: packet-broker P4 configuration daemon
### END INIT INFO

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
LOG=/var/log/packet-broker-configd

. /lib/lsb/init-functions

CONFIG_DIR=/etc/packet-broker
IFMIBS_DIR=/var/run/packet-broker
CONNECT_RETRIES=30
## Must define ${BASE}
test -f /etc/default/packet-broker
source /etc/default/packet-broker

SDE=${BASE}/bf-sde-9.1.0
TOOLS=${BASE}/tools
DAEMON=${BASE}/packet-broker/configd.py

cd $SDE
source $TOOLS/set_sde.bash

test -x $DAEMON || exit 5

PIDFILE=/var/run/pb-configd.pid

case $1 in
    start)
        mkdir -p $IFMIBS_DIR
        log_daemon_msg "Starting packet-broker configuration daemon" "pb-configd"
        set +e
        start-stop-daemon --start --make-pidfile --pidfile $PIDFILE \
                          --startas $DAEMON --background --no-close \
                          -- --config-dir $CONFIG_DIR --ifmibs-dir $IFMIBS_DIR \
                          --connect-retries $CONNECT_RETRIES >>$LOG 2>&1
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping packet-broker configuration daemon" "pb-configd"
        start-stop-daemon --remove-pidfile --pidfile $PIDFILE --stop --startas $DAEMON --retry=INT/30/KILL/5
        log_end_msg $?
        ;;
    restart|force-reload)
        $0 stop && sleep 2 && $0 start
        ;;
    reload)
        kill -HUP $(cat $PIDFILE)
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON "Packet-broker configuration daemon"
        ;;
    *)
	echo "Usage: $0 {start|stop|restart|force-reload|reload|status}"
	exit 2
	;;
esac
